### ISSUE TITLE
Library not working at all

### ISSUE THREAD

**Issue by LinusGeffarth** [evanplaice/jquery-csv#98]
# Subject of the issue

Library not working at all

## Description

I have installed the package onto my server via `npm` - without any errors. I tried importing the plugin into my project. However, when doing `$.csv.toArray(csv)` I get the console error <a href="#actual-behavior">below</a>. I then tried to open the example site provided. Same result: the library does not work and outputs said console error.  
Am I doing something wrong or what else is up?

## Environment

- Platform: Browser 
- Version: Chrome 50
- Usage: Load from file

## Steps to reproduce

- opened example site

## Expected behaviour

- examples should work...

<h2 id="actual-behavior">Actual behaviour</h2>

- examples do not work
- console error message: 

>Uncaught TypeError: Cannot read property 'toArray' of undefined

**Comment by evanplaice** [comment]
Thanks for posting an issue. For some reason, the last 2 releases (ie 0.8.4 and 0.8.5) on CDNJS aren't working.

The docs are sorely in need of an update, to fix some old/broken links and bring everything up-to-date. I'm fixing that now.

**Comment by LinusGeffarth** [comment]
Ah okay. Thanks for your quick response!

Is there any workaround I can use for now or are you going to push a commit in the next few days anyway?

**Comment by evanplaice** [comment]
I just pushed the changes as v0.8.6. Documentation should work now.

The examples contained a bunch of old links that still pointed to Google Code, from when it was hosted there. Looks like Google Code just finished removing all traces of public projects. Anyway, everything should 'just work' now.

If you're using the minified bundle, try the non-minified version and let me know if it works any better.

CDNJS is still broken for now. I'm still looking into a fix.

**Comment by LinusGeffarth** [comment]
Hmm I don't know. I have updated (`npm update`) and installed (`npm install jquery-csv`) the package and now its version says `0.8.6` but when I open `/jquery-csv/examples/basic-usage.html`, the console errors still show and the result tables are still empty...
Do I have to do anything else to *actually* update or is it something else?

**Comment by evanplaice** [comment]
The lib should require no external dependencies to run except for development.

The jquery.csv.js source hasn't been modified in quite some time. I'm still working on improving testing before I make any significant changes.

The examples do point to a CDN copy of jquery + jquery-ui; if either of those don't load for some reason that could be the source of some issues.

**If you don't mind, could you post the errors?**

**Can you try loading the examples directly from GitHub (ie via the readme link)?**

**Are you using NPM 5+? If so, try running the tests with?**

```bash
npx mocha test/test.js
```

*Note: If you're unfamiliar with NPX, it's just like `npm run` except it'll download a temporary copy of any missing dependencies required to run the command. It saves from having to load the whole devDependency list.*

----

I just tried cloning a fresh copy on my own machine and everything worked as expected. If I were to guess, I think the lib itself is fine and one of the dependencies required by the demo is getting blocked for some reason.

**Comment by LinusGeffarth** [comment]
It seems like the sample site is still pointing to google code:

>GET http://jquery-csv.googlecode.com/git/src/jquery.csv.js net::ERR_ABORTED

>Uncaught TypeError: Cannot read property 'toArray' of undefined

I have installed NPM yesterday, but `npm --version` returns 3.5.2. Does that have anything to do with it?  
I'll try downloading the source from Github manually...

**Comment by evanplaice** [comment]
Is there anything preventing you from deleting the jquery-csv directory altogether? It sounds like you're still running from an outdated version.

If you installed via npm, do `npm remove --save jquery-csv && npm install --save jquery-csv`.

The NPM version shouldn't matter. NPM 5+ is just a new feature introduced in the latest major release. If you have mocha installed globally, you can still run the tests using `mocha test/test.js`. Or, if you install the devDependencies you can run them using `npm run mocha test/test.js`. I just make it a habit to avoid telling users to install any extras unless they plant to contribute.

**Comment by evanplaice** [comment]
Awesome, I'm glad you got it working and appreciate your patience. It has been a while since I looked at the example code. I didn't realize how out-of-date they were.

I'll keep an eye out to see if anybody else has issues. I have experienced a weird stale cache issue with NPM once before. Hopefully, this isn't the same sort of thing.
